config/routes.rb
FumbleS2::Application.routes.draw do
  
  ActiveAdmin.routes(self)

  resources :picks
  resources :week, :only => [:index, :show]
  resources :standingslive, :only => :index

  #match '/users', :to => 'standings#index'
  match '/user/:id', :to => 'users#show'
  match '/user' => redirect('/users')

  authenticated :user do
    root :to => 'home#index'
  end
  root :to => "home#index"
  devise_for :users
  resources :users, :only => [:show, :index]
  resources :results, :only => [:show, :index]
end

app/models/pick.rb
class Pick < ActiveRecord::Base
  attr_accessible :home_win_pick, :winner_id, :away_score_pick, :home_score_pick, :game_id, :user_id
  attr_accessor :winner_id

  belongs_to :game
  belongs_to :user
  belongs_to :week

  validates :game_id, :presence => true
  validates :user_id, :presence => true

  validates_numericality_of :away_score_pick, :allow_nil => true,
                                              :only_integer => true,
                                              :less_than => 100,
                                              :greater_than_or_equal_to => 0,
                                              :message => 'Only integer scores 0-99 allowed.'
  validates_numericality_of :home_score_pick, :allow_nil => true,
                                              :only_integer => true,
                                              :less_than => 100,
                                              :greater_than_or_equal_to => 0,
                                              :message => 'Only integer scores 0-99 allowed.'

  validates_inclusion_of :home_win_pick,  :in => [true,false],
                                          :message => 'Missing the home_win_pick'                                            
  
  before_save :change_winner_id

  def change_winner_id
  	if !self.winner_id.nil?
  		logger.info self.winner_id == self.game.away_team_id
  		if self.winner_id == self.game.away_team_id
  			self.home_win_pick = false
  			return true
  		elsif self.winner_id == self.game.home_team_id
  			self.home_win_pick = true
        return true
  		else
  			return false
  		end
  	end
  end

  def winner
  	if self.home_win_pick == true
  		self.game.home_team
  	elsif self.home_win_pick == false
  		self.game.away_team
  	end
  end

  def points_display
    if self.game.points_req
      "#{self.away_score_pick} - #{self.home_score_pick}"
    else
      nil
    end
  end

  def points_earned
    if self.game.points_req

        ap = self.away_score_pick
        hp = self.home_score_pick

      if !self.game.score.nil?
        as = self.game.score.away_score
        hs = self.game.score.home_score
      else
        as = 0
        hs = 0
      end

      p1 = (ap - as).abs
      p2 = (hp - hs).abs
      p3 = ((ap + hp) - (as + hs)).abs
      p4 = 2*((ap - hp) - (as - hs)).abs
  
      pts = p1 + p2 + p3 + p4

      return pts
    end 
  end

  def winning?
    if self.home_win_pick
      self.game.score.away_score < self.game.score.home_score
    else
      self.game.score.away_score > self.game.score.home_score
    end
  end

  def correct?
    if !self.game.score.nil?
      if self.game.score.final
        self.winning?
      else
        return nil
      end
    else
      return nil
    end
  end
end

app/controllers/picks_controller.rb
class PicksController < ApplicationController
  
  include ApplicationHelper
  before_filter :authenticate_user!

  def index
    define_week
    @week = @pick_week
    @picks = current_user.picks.includes(:game => [:home_team, :away_team]).where(:games => {:week_id => @week}).order("picks.user_id ASC,games.points_req ASC, games.start_time ASC, picks.game_id ASC")
  end

  def new
  	define_week
    @week = @pick_week

    if Time.now > @deadline
      flash[:error] = 'Nice Try! Pick deadline passed. Contact the Administrator'
      redirect_to :picks
    end

    @all_picks = Pick.new
    @week_games = week_games_picked(@week) 
    @prior_picks = current_user.picks.includes(:game => [:home_team, :away_team]).where(:games => {:week_id => @week}).order("picks.user_id ASC,games.points_req ASC, games.start_time ASC, picks.game_id ASC")


  end

  def create
    define_week
    @week = @pick_week
    @user = current_user

    if Time.now > @deadline
      flash[:error] = 'Nice Try! Pick deadline passed. Contact the Administrator'
      redirect_to :picks
    else
      @all_picks = Pick.new
      @week_games = week_games_picked(@week)
      
      picks = params[:all_picks]
    # "all_picks"=>{"6"=>{"winner_id"=>"103"},
    # "16"=>{"winner_id"=>"227"},...},
      points_pick = params[:points_pick]
    # "points_pick"=>{"37"=>{"away_score_pick"=>"2",
    # "home_score_pick"=>"23"}},

      if picks.keys.count != @week_games.count
        flash[:error] = 'Missing a pick'
        render 'new'
      end
      
      picks.keys.each do |game_id|
        pick = current_user.picks.find_or_initialize_by_game_id(game_id.to_i) 
        pick.winner_id = picks[game_id].values[0].to_i
        if !points_pick.nil?
          if points_pick[game_id]
            pick.away_score_pick = points_pick[game_id.to_s]["away_score_pick"].to_i
            pick.home_score_pick = points_pick[game_id.to_s]["home_score_pick"].to_i
          end
        end
        pick.change_winner_id
        pick.save!

      end
      PickSubmission.pick_submit_confirmation(@user,@user.week_picks(@week)).deliver
      flash[:success] = "Picks updated. Check your email for confirmation."
      redirect_to (:picks)
    end
  end

end

private

def find_pick_week
  Time.zone = 'Eastern Time (US & Canada)'
  
  if Time.now < current_week.pick_deadline
    @week = current_week
  else
    @week = next_week
  end

  @deadline = @week.pick_deadline
end

app/helpers/picks_helper.rb
module PicksHelper

end

app/views/picks/index.html.erb
<h1>Week <%= @week.season_week %></h1>

<% if @deadline - 1.hour > Time.now %>
  <h2><%= "Picks due: #{(@deadline - 1.hour).strftime('%a, %l%p %Z')} or about #{time_ago_in_words(@deadline - 1.hour)} from now" %></h2>
  <span><%= link_to 'Edit', new_pick_path, class: "btn btn-small btn-primary pull-right" %></span>
<% elsif @deadline > Time.now %>
  <h2><%= "Picks due: #{(@deadline - 1.hour).strftime('%a, %l%p %Z')} or about #{time_ago_in_words(@deadline - 1.hour)} ago" %></h2>
  <span><%= link_to 'Edit', new_pick_path, class: "btn btn-small btn-primary pull-right" %></span>
<% else %>
  <h2>Picks Official</h2>
<% end %>
<table class="table">
  <thead>
    <tr>
      <th>Date and Time</th>
      <th>Away Team</th>
      <th>Home Team</th>
    </tr>
  </thead>
  <tbody>
    <% @picks.each do |pick| %>
      <tr>
        <td><%= link_to "#{pick.game.start_time.strftime("%a, %b %d %I:%M %p")} #{pick.game.start_time.zone}", 
                "http://scores.espn.go.com/ncf/gamecast?gameId=#{pick.game.espn_game_id}", target: "_blank" %></td>
        <td>
          <% if pick.home_win_pick %>
            <%= "#{pick.game.away_team.name}</td><td><strong>#{pick.game.home_team.name}</strong>".html_safe %>
          <% else %>
            <%= "<strong>#{pick.game.away_team.name}</strong></td><td>#{pick.game.home_team.name}".html_safe %>
          <% end %>
        </td>
      </tr>
      <% if pick.game.points_req %>
        <tr>
          <td>Points Pick</td>
          <td><%= pick.away_score_pick %></td>
          <td><%= pick.home_score_pick %></td>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

app/views/picks/new.html.erb
<% provide(:title, "Make your week #{@week.season_week} selections") %>
<h1><%="Make your week #{@week.season_week} selections"%></h1>
<% if @deadline - 1.hour > Time.now %>
  <h2><%= "Picks due: #{(@deadline - 1.hour).strftime('%a, %l%p %Z')} or about #{time_ago_in_words(@deadline - 1.hour)} from now" %></h2>
<% else %>
  <h2><%= "Picks due: #{(@deadline - 1.hour).strftime('%a, %l%p %Z')} or about #{time_ago_in_words(@deadline - 1.hour)} ago" %></h2>
<% end %>
<%= form_for(@all_picks) do |f| %>
  <table class="table">
    <thead>
      <tr>
        <th>Date and Time</th>
        <th>Away Team</th>
        <th>Home Team</th>
      </tr>
    </thead>
    <tbody>
      <% @week_games.each do |g| %>
        <tr>
          <td><%= "<a href=\"http://scores.espn.go.com/ncf/gamecast?gameId=#{g.espn_game_id}\" target=\"_blank\">".html_safe %><%= g.start_time.strftime("%A, %b %d at %I:%M %p") %> <%= g.start_time.zone %></td>
          <div class ="controls">
            <% if !@prior_picks.where(game_id: g)[0].nil? && !@prior_picks.where(game_id: g)[0].home_win_pick%>
                <td><label class="radio"><%= radio_button_tag "all_picks[#{g.id}][winner_id]",g.away_team_id, true%><%= g.away_team.name %></label></td>
                <td><label class="radio"><%= radio_button_tag "all_picks[#{g.id}][winner_id]",g.home_team_id%><%= g.home_team.name %></label></td>
              <% else %>
                <td><label class="radio"><%= radio_button_tag "all_picks[#{g.id}][winner_id]",g.away_team_id %><%= g.away_team.name %></label></td>
                <td><label class="radio"><%= radio_button_tag "all_picks[#{g.id}][winner_id]",g.home_team_id, true%><%= g.home_team.name %></label></td>
            <% end %>
          </div>
        </tr>
        <% if g.points_req %>
          <tr>
            <td>Points Pick</td>
            <% if !@prior_picks.where(game_id: g)[0].nil? && !@prior_picks.where(game_id: g)[0].away_score_pick.nil?%>
              <td><%= number_field_tag "points_pick[#{g.id}][away_score_pick]", @prior_picks.where(game_id: g)[0].away_score_pick, :in => 0..99, :maxlength => 2, :required => true %></td>
              <td><%= number_field_tag "points_pick[#{g.id}][home_score_pick]", @prior_picks.where(game_id: g)[0].home_score_pick, :in => 0..99, :maxlength => 2, :required => true %></td>
            <% else %>
              <td><%= number_field_tag "points_pick[#{g.id}][away_score_pick]", nil, :in => 0..99, :maxlength => 2, :placeholder => g.away_team.name, :required => true %></td>
              <td><%= number_field_tag "points_pick[#{g.id}][home_score_pick]", nil, :in => 0..99, :maxlength => 2, :placeholder => g.home_team.name, :required => true %></td>
            <% end %>
          </tr>
        <% end %>
      <% end %>
    </tbody>
  </table>
  <%= f.submit "Submit Picks", class: 'btn btn-primary' %>
<% end %>