config/routes.rb
FumbleS2::Application.routes.draw do
  
  ActiveAdmin.routes(self)

  resources :picks
  resources :week, :only => [:index, :show]
  resources :standingslive, :only => :index

  #match '/users', :to => 'standings#index'
  match '/user/:id', :to => 'users#show'
  match '/user' => redirect('/users')

  authenticated :user do
    root :to => 'home#index'
  end
  root :to => "home#index"
  devise_for :users
  resources :users, :only => [:show, :index]
  resources :results, :only => [:show, :index]
end

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
    <a class="close" data-dismiss="alert">×</a>
    <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
  </div>
<% end %>

app/views/layouts/_navigation.html.erb
<a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
  <span class="icon-bar"></span>
  <span class="icon-bar"></span>
  <span class="icon-bar"></span>
</a>
<%= link_to "Fumble Club 2012", root_path, :class => 'brand' %>

<div class="nav-collapse">
<ul class="nav">
  <% if user_signed_in? %>
    <li class="divider-vertical"></li>
    <li>
      <%= link_to "Make Picks", picks_path %>
    </li>
    <li class="divider-vertical"></li>
    <li><%= link_to "Weeks", week_index_path %></li>
    <li class="divider-vertical"></li>
    <li><%= link_to "Results", results_path %></li>
    <li class="divider-vertical"></li>
  <% end %>
</ul>
<ul class="nav pull-right">
  <% if user_signed_in? %>
    <% if current_user.has_role? :admin %>
    <li class="divider-vertical"></li>
      <li>
        <%= link_to 'Live', '/standingslive' %>
      </li>
      <li class="divider-vertical"></li>
      <li>
        <%= link_to 'Admin', '/admin' %>
      </li>
    <% end %>
      <li class="divider-vertical"></li>
      <li class="visible-desktop">
        <% if !current_user.name.nil? %> 
          <%= link_to "#{current_user.name}", edit_user_registration_path %>
        <% else %>
          <%= link_to "#{current_user.email}", edit_user_registration_path %>
        <% end %>
      </li>
      <li class="divider-vertical"></li>
    <li>
      <%= link_to 'Logout', destroy_user_session_path, :method=>'delete' %>        
    </li>
  <% else %>
    <li class="divider-vertical"></li>
    <li class="dropdown">
      <a class="dropdown-toggle" href="#" data-toggle="dropdown">Sign In <strong class="caret"></strong></a>
      <div class="dropdown-menu navlogin" role="menu" aria-labelledby="dLabel">
        <%= render 'layouts/navlogin' %>
      </div>
    </li>
  <% end %>
</ul>

app/views/layouts/_navlogin.html.erb
<%= simple_form_for(resource, :as => resource_name, :url => session_path(resource_name)) do |f| %>
  <div class="form-inputs">
    <%= f.input :email, placeholder: 'user@domain.com', required: false, autofocus: true, label: false, input_html: { class: 'span2' } %>
    <%= f.input :password, placeholder: 'password', required: false, label: false, input_html: { class: 'span2' } %>
    <%= f.input :remember_me, as: :boolean, label: false, inline_label: 'Remember Me' if devise_mapping.rememberable? %>
  </div>
  <%= f.button :submit, 'Sign in', class: 'span2 btn-large btn-block btn-primary' %>
<% end %>

app/views/layouts/application.html.erb
<!doctype html>
<html>
  <head>
    <%= favicon_link_tag 'football.ico' %>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Fumble Club 2012" %></title>
    <meta name="description" content="">
    <meta name="author" content="">
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->
    <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <%= yield(:head) %>
  </head>
  <body>
    <header class="navbar navbar-fixed-top navbar-inverse">
      <nav class="navbar-inner">
        <div class="container-fluid">
          <%= render 'layouts/navigation' %>
        </div>
      </nav>
    </header>
    <div id="main" role="main">
      <div class="container-fluid">
        <div class="content">
           <div class="row">
            <div class="span12">
              <%= render 'layouts/messages' %>
              <%= yield %>
            </div>
          </div>
          <footer>
          </footer>
        </div>
      </div> <!--! end of .container-fluid -->
    </div> <!--! end of #main -->
    <% if Rails.env == 'development' %>
      <script>document.write('<script src="http://' + (location.host || 'localhost').split(':')[0] + ':35729/livereload.js?snipver=1"></' + 'script>')</script>
    <% end %>
    <% # if Rails.env == 'production' %>
      <script type="text/javascript">
        var _gaq = _gaq || [];
        _gaq.push(['_setAccount', 'UA-34295037-1']);
        _gaq.push(['_setDomainName', 'fumbleclub.com']);
        _gaq.push(['_trackPageview']);

        (function() {
          var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
          ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
          var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
        })();
      </script>
    <% # end %>
  </body>
</html>